// Converted Translation sketch from in JavaScript (Processing.compile)

// this code was autogenerated from PJS
(function($p) {

    var x = 0,
        y = 0;
    var dim = 80.0;

    function setup() {
        $p.size(640, 360);
        $p.noStroke();
    }
    $p.setup = setup;

    function draw() {
        $p.background(102);

        x = x + 0.8;

        if (x > $p.width + dim) {
            x = -dim;
        }

        $p.translate(x, $p.height / 2 - dim / 2);
        $p.fill(255);
        $p.rect(-dim / 2, -dim / 2, dim, dim);

        $p.translate(x, dim);
        $p.fill(0);
        $p.rect(-dim / 2, -dim / 2, dim, dim);
    }
    $p.draw = draw;
})
